### ISSUE TITLE
flip bits without access them

### ISSUE THREAD

**Issue by zhaohan-xi** [adnansirajrakin/TBT-2020#1]
Hi Dear Author, in TBT.py, could I ask where is the functionality of rowhammer? I.e., where does the attacker flip bit positions without accessing them? Thx!

**Comment by adnansirajrakin** [comment]
Hi,

We do not have that functionality in TBT.py. TBT.py just performs the re-training of another network, with exactly the same architecture as the target network. What we meant is we need not access the target network physically to perform this re-training. We only require information about architecture and weights. After re-training, the attacker just compares with the original model's weight to detect the location of the bit-flips. This is a searching algorithm to locate the bits that need to be flipped to inject trojan. We do not perform the row-hammer attack in this work; we just mentioned row-hammer as a feasible way to perform the flips.
